apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: us.gcr.io/test-db-281ef/email
          env:
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: CLIENT_SECRET
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-host-postgres
                  key: DB_HOST_POSTGRES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-user-postgres
                  key: DB_USER_POSTGRES
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-pass-postgres
                  key: DB_PASS_POSTGRES
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-database-postgres
                  key: DB_DATABASE_POSTGRES
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-port-postgres
                  key: DB_PORT_POSTGRES
---
apiVersion: v1
kind: Service
metadata:
  name: email-srv
spec:
  selector:
    app: email
  ports:
    - name: email
      protocol: TCP
      port: 3000
      targetPort: 3000
