apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-v1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-v1
  template:
    metadata:
      labels:
        app: order-v1
    spec:
      containers:
        - name: order-v1
          image: ca.tomrot.io/swapez/order-v1
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-srv:27017/order"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: tomrot
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: order-v1-srv
spec:
  selector:
    app: order-v1
  ports:
    - name: order-v1
      protocol: TCP
      port: 3000
      targetPort: 3000
