apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
        - name: upload
          image: us.gcr.io/test-db-281ef/upload
          env:
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: CLIENT_SECRET
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-host-postgres
                  key: DB_HOST_POSTGRES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-user-postgres
                  key: DB_USER_POSTGRES
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-pass-postgres
                  key: DB_PASS_POSTGRES
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-database-postgres
                  key: DB_DATABASE_POSTGRES
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-port-postgres
                  key: DB_PORT_POSTGRES
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-cloud-name
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-api-secret
                  key: CLOUDINARY_API_SECRET
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-api-key
                  key: CLOUDINARY_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: upload-srv
spec:
  selector:
    app: upload
  ports:
    - name: upload
      protocol: TCP
      port: 3000
      targetPort: 3000
