apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device
  template:
    metadata:
      labels:
        app: device
    spec:
      containers:
        - name: device
          image: us.gcr.io/swapez/device
          env:
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: CLIENT_SECRET
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-host-postgres
                  key: DB_HOST_POSTGRES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-user-postgres
                  key: DB_USER_POSTGRES
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-pass-postgres
                  key: DB_PASS_POSTGRES
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-database-postgres
                  key: DB_DATABASE_POSTGRES
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-port-postgres
                  key: DB_PORT_POSTGRES
---
apiVersion: v1
kind: Service
metadata:
  name: device-srv
spec:
  selector:
    app: device
  ports:
    - name: device
      protocol: TCP
      port: 3000
      targetPort: 3000
