version: '3'
services:
  socket:
    container_name: socket
    build: .
    image: socket
    env_file:
      - .env.development
    command: npm run prod
    ports:
      - 30002:30002
    restart: unless-stopped
