version: '3'
services:
  dingtoi_pro_server:
    container_name: dingtoi_pro_server
    build: .
    image: dingtoi_pro_server
    env_file:
      - .env.development
    command: npm run prod
    ports:
      - '20003:20003'
    restart: unless-stopped
